# Generated by Django 6.0.7 on 2026-07-25 17:11

import partners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerregistration',
            name='accepted_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='annual_passenger_volume',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='business_types',
            field=models.CharField(blank=True, help_text='Comma-separated: FIT, Groups, MICE', max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='company_profile_file',
            field=models.FileField(blank=True, upload_to=partners.models.partner_upload_to),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='company_registration_country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='designation',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='logo_file',
            field=models.FileField(blank=True, upload_to=partners.models.partner_upload_to),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='main_destinations_sold',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='markets_served',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='mobile',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='passport_id_file',
            field=models.FileField(blank=True, upload_to=partners.models.partner_upload_to),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='postal_code',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='preferred_currency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='telephone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='trade_license_file',
            field=models.FileField(blank=True, upload_to=partners.models.partner_upload_to),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='vat_certificate_file',
            field=models.FileField(blank=True, upload_to=partners.models.partner_upload_to),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='vat_tax_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='partnerregistration',
            name='year_established',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
