# Generated by Django 6.0.7 on 2026-07-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_path',
            field=models.CharField(blank=True, help_text='Static path under ms/, e.g. uploads/testimonial/t1.jpg', max_length=255),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Public submissions start unpublished until staff approves.'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, help_text='Travel dates display, e.g. 01 Sep 2024 to 02 Sep 2024', max_length=180),
        ),
    ]
