# Generated by Django 6.0.7 on 2026-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofile',
            name='credit_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='guestprofile',
            name='credit_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
