# Generated by Django 6.0.7 on 2026-07-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(blank=True, max_length=255)),
                ('prebook_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('liteapi_booking_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('hotel_confirmation_code', models.CharField(blank=True, max_length=255)),
                ('hotel_id', models.CharField(blank=True, max_length=64)),
                ('hotel_name', models.CharField(blank=True, max_length=255)),
                ('check_in', models.DateField(blank=True, null=True)),
                ('check_out', models.DateField(blank=True, null=True)),
                ('adults', models.PositiveSmallIntegerField(default=2)),
                ('guest_first_name', models.CharField(max_length=100)),
                ('guest_last_name', models.CharField(max_length=100)),
                ('guest_email', models.EmailField(max_length=254)),
                ('guest_phone', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=32)),
                ('raw_prebook', models.JSONField(blank=True, default=dict)),
                ('raw_book', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
