# Generated by Django 6.0.7 on 2026-07-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='credit_charged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
